apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: fluid-properties
  name: fluid-properties
  namespace: components-selector
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fluid-properties
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fluid-properties
    spec:
      containers:
      - image: bogmilos/fluid-properties:2.0.5
        imagePullPolicy: IfNotPresent
        name: fluid-properties
        resources: {}
      restartPolicy: Always
