apiVersion: v1
kind: Service
metadata:
  labels:
    app: fluid-properties
  name: fluid-properties
  namespace: components-selector
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: fluid-properties
  type: NodePort
